### PR TITLE
added reset_errors_before_recovery_parameter from ros_canopen

### PR DESCRIPTION
**Pull request by jabbenseth**
see https://github.com/ros-industrial/ros_canopen/pull/234

### CODE REVIEW

**Comment by jabbenseth** [comment]
@ipa-mdl wanted to check the order of loading the parameters

**Comment by fmessmer** [comment]
@ipa-jba is this final?
`raw3-3` tuned, running `ros_canopen` and behavior acceptable?

**Comment by mathias-luedtke** [comment]
> is this final?

Not yet, I need to review it.

>  raw3-3 tuned, running ros_canopen and behavior acceptable?

UM=2 did the trick (again), works like a charm :)

**Comment by fmessmer** [comment]
I'll merge this and rebase it for a cleaner commit history in https://github.com/ipa320/cob_robots/pull/661

**Pull request merged**
